# Generated by Django 3.1.2 on 2020-11-15 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_employee', models.ImageField(blank=True, null=True, upload_to='images/employee/%Y/%m/%d')),
                ('nom_employee', models.CharField(max_length=20)),
                ('prenom_employee', models.CharField(max_length=20)),
                ('telephone_employee', models.CharField(max_length=20)),
                ('email_employee', models.EmailField(max_length=254)),
                ('localisation_employee', models.CharField(choices=[('antananarivo', 'Antananarivo'), ('antsiranana', 'Antsiranana'), ('fianarantsoa', 'Fianarantsoa'), ('toamasina', 'Toamasina'), ('mahajanga', 'Mahajanga'), ('toliara', 'Toliara')], max_length=20)),
                ('adresse_employee', models.CharField(max_length=20)),
                ('disponibilite_employee', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['nom_employee', 'prenom_employee'],
            },
        ),
        migrations.CreateModel(
            name='Fonctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fonction', models.CharField(max_length=20)),
                ('salaire_fonction', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Fonction',
                'verbose_name_plural': 'Fonctions',
                'ordering': ['nom_fonction'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_image', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Lieux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lieu', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Lieu',
                'verbose_name_plural': 'Lieux',
                'ordering': ['nom_lieu'],
            },
        ),
        migrations.CreateModel(
            name='Marques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_marque', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'ordering': ['nom_marque'],
            },
        ),
        migrations.CreateModel(
            name='Vehicules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_vehicule', models.ImageField(blank=True, null=True, upload_to='images/vehicle/%Y/%m/%d/')),
                ('immatriculation_vehicule', models.CharField(max_length=20)),
                ('modele_vehicule', models.CharField(max_length=20)),
                ('moteur_vehicule', models.CharField(max_length=20)),
                ('capacite_vehicule', models.IntegerField()),
                ('disponibilite_vehicule', models.BooleanField(default=True)),
                ('marque_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marques')),
            ],
            options={
                'verbose_name': 'Vehicule',
                'verbose_name_plural': 'Vehicules',
                'ordering': ['marque_vehicule'],
            },
        ),
        migrations.CreateModel(
            name='Voyages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couverture_voyage', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('nom_voyage', models.CharField(max_length=20)),
                ('prix_voyage', models.IntegerField()),
                ('place_voyage', models.PositiveSmallIntegerField()),
                ('date_voyage', models.DateField()),
                ('duree_voyage', models.IntegerField()),
                ('description_voyage', models.TextField()),
                ('slug', models.SlugField(blank=True)),
                ('chauffeur_voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='app.employees')),
                ('lieu_voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lieux')),
                ('photo_autres', models.ManyToManyField(to='app.Images')),
                ('responsable_voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to='app.employees')),
                ('vehicule_voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicules')),
            ],
            options={
                'verbose_name': 'Voyage',
                'verbose_name_plural': 'Voyages',
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_place', models.IntegerField()),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('paiement', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.voyages')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['client'],
            },
        ),
        migrations.AddField(
            model_name='employees',
            name='fonction_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fonctions'),
        ),
    ]
